### ISSUE TITLE
Mod breaks game balance and obsoletes starter relic for IronClad

### ISSUE THREAD

**Issue by AvangionQ** [deengames/slay-the-spire-easy-mode-mod#1]
This would make the Ironclad's class relic worthless, as well as obsoleting other acquired relics such as the Blood Vial ... hope you take that into account, make it so any end-of-combat healing relics in your inventory give Temporary HP at the start of your combats.

**Comment by nightblade9** [comment]
Hey, not sure I understand exactly your proposal. Are you saying:

- If you have any relics like Ironclad's class relic, make them heal at the beginning instead of the end of combat
- Modify this mod so it heals at the beginning, not end of combat
- Something else

**Comment by AvangionQ** [comment]
Something else. If you heal to full at end of combat with this mod, it makes the Ironclad's class relic useless. Meaning, you'll need to somehow supplement the functionality of those class relics in order to preserve balance between the classes. My suggestion was that if you have this mod enabled and Burning Blood, Black Blood or some other relic that heals at end of encounter, give the player temporary HP at the start of the encounter. If that doesn't work for you, maybe give them +1 maxHP each time they gain healing from a relic other than the one your mod uses.

Edit: give Black Blood +2 maxHP (as it's supposed to be an improvement over Burning Blood)

PS, looking forward to giving your mod a try 🥇

**Comment by nightblade9** [comment]
To offset this, I used to play IronClad and request the fourth option (trade starter for a different relic). But, I think gaining health at the end of the battle creates some disparities:

- The IronClad starting relic becomes worthless, as does the black flame one
- You can easily win those events where you lose HP (eg. lose HP to gain a chance at a relic)
- In some cases, you enter a strong battle with diminished HP and can get wrecked

Instead, I will  update the mod (v1.1.0 release) to heal you at the beginning of battle. This makes the above points (starting relic, HP-loss events) still strategic.

Thanks for your feedback.

**Comment by nightblade9** [comment]
Done. If you try the mod, please let me know your feedback. (FYI, you will have to build it from source - I haven't figured out how to upload it to the Steam Workshop yet.)
